services:
  metabase:
    image: metabase/metabase:latest
    container_name: job-metabase
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - job_metabase_data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db

volumes:
  job_metabase_data:
