#!/usr/bin/env python3
"""Import the final verified source candidate CSV into the sources table."""

from __future__ import annotations

import argparse
import asyncio
import csv
from pathlib import Path

from app.models import PlatformType
from app.services.verified_source_import import EligibleSourceCandidate, import_candidates


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Import verified source candidates into the sources table.",
    )
    parser.add_argument(
        "--input",
        default="reports/final_source_import_candidates.csv",
        help="CSV path generated by build_final_source_candidates.py.",
    )
    return parser


def load_input(path: Path) -> list[EligibleSourceCandidate]:
    candidates: list[EligibleSourceCandidate] = []
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            candidates.append(
                EligibleSourceCandidate(
                    platform=PlatformType(str(row["platform"]).strip()),
                    name=str(row["name"]).strip(),
                    identifier=str(row["identifier"]).strip(),
                    url=str(row["url"]).strip(),
                    job_count=int(row["job_count"]),
                )
            )
    return candidates


async def run(args: argparse.Namespace) -> int:
    input_path = Path(args.input).expanduser().resolve()
    if not input_path.exists():
        raise SystemExit(f"Input CSV does not exist: {input_path}")

    candidates = load_input(input_path)
    inserted, skipped = await import_candidates(
        candidates,
        notes_prefix="Imported from verified ATS audit candidate list on 2026-02-28",
    )

    print(f"input={input_path}")
    print(f"candidate_rows={len(candidates)}")
    print(f"inserted={inserted}")
    print(f"skipped={skipped}")
    return 0


def main() -> None:
    raise SystemExit(asyncio.run(run(build_parser().parse_args())))


if __name__ == "__main__":
    main()
